const wilayasenfrancais = [
  { code: 1,  name: "adrar" },
  { code: 2,  name: "chlef" },
  { code: 3,  name: "laghouat" },
  { code: 4,  name: "oum el bouaghi" },
  { code: 5,  name: "batna" },
  { code: 6,  name: "bejaia" },
  { code: 7,  name: "biskra" },
  { code: 8,  name: "béchar" },
  { code: 9,  name: "blida" },
  { code: 10, name: "bouira" },
  { code: 11, name: "tamanrasset" },
  { code: 12, name: "tébessa" },
  { code: 13, name: "tlemcen" },
  { code: 14, name: "tiyaret" },
  { code: 15, name: "tizi ouzou" },
  { code: 16, name: "alger" },
  { code: 17, name: "djelfa" },
  { code: 18, name: "jijel" },
  { code: 19, name: "setif" },
  { code: 20, name: "saida" },
  { code: 21, name: "skikda" },
  { code: 22, name: "sidi bel abbès" },
  { code: 23, name: "annaba" },
  { code: 24, name: "guelma" },
  { code: 25, name: "constantine" },
  { code: 26, name: "médéa" },
  { code: 27, name: "mostaganem" },
  { code: 28, name: "m’sila" },
  { code: 29, name: "maâsara" }, 
  { code: 30, name: "ouargla" },
  { code: 31, name: "oran" },
  { code: 32, name: "el bayadh" },
  { code: 33, name: "illizi" },
  { code: 34, name: "bordj bou arreridj" },
  { code: 35, name: "boumerdès" },
  { code: 36, name: "el tarf" },
  { code: 37, name: "tindouf" },
  { code: 38, name: "tissemsilt" },
  { code: 39, name: "el oued" },
  { code: 40, name: "khenchela" },
  { code: 41, name: "souk ahras" },
  { code: 42, name: "tipaza" },
  { code: 43, name: "mila" },
  { code: 44, name: "ain defla" },
  { code: 45, name: "naama" },
  { code: 46, name: "ain temouchent" },
  { code: 47, name: "ghardaia" },
  { code: 48, name: "relizane" },
  { code: 49, name: "timimoun" },
  { code: 50, name: "bordj baji mokhtar" },
  { code: 51, name: "oulad jellal" },
  { code: 52, name: "beni abbes" },
  { code: 53, name: "ain saleh" },
  { code: 54, name: "ain gazem" },
  { code: 55, name: "touggourt" },
  { code: 56, name: "janet" },
  { code: 57, name: "el meghair" },
  { code: 58, name: "el meniaa" }
];